services:
  mw-target:
    build:
      context: .
      dockerfile: Dockerfile
    restart:
      unless-stopped
    ports:
      - 2000:2000   # Target Process
      - 2001:80     # Http Server
      - 2002:2002   # Exploit Reverse Shell
      - 2003:2003   # Persistent Backdoor Shell
      - 2004:22     # SSH
